import type { IconType } from "react-icons"
import { BsFillBootstrapFill, BsRobot } from "react-icons/bs"
import {
  SiApollographql,
  SiChakraui,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiGatsby,
  SiGit,
  SiGithub,
  SiGraphql,
  SiJavascript,
  SiJest,
  SiJquery,
  SiLaravel,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiOpenapiinitiative,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiPwa,
  SiReact,
  SiRedux,
  SiShadcnui,
  SiSocketdotio,
  SiStorybook,
  SiStyledcomponents,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiWebpack,
  SiWordpress,
  SiWxt,
} from "react-icons/si"

export type Stack = {
  name: string
  icon: IconType
  className?: string
}

export const STACKS = [
  { name: "PHP", icon: SiPhp, className: "text-blue-500" },
  { name: "JavaScript", icon: SiJavascript, className: "text-yellow-400" },
  { name: "TypeScript", icon: SiTypescript, className: "text-blue-400" },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "React", icon: SiReact, className: "text-sky-500" },
  { name: "Tailwind CSS", icon: SiTailwindcss, className: "text-cyan-300" },
  { name: "shadcn/ui", icon: SiShadcnui },
  {
    name: "Bootstrap",
    icon: BsFillBootstrapFill,
    className: "text-purple-500",
  },
  { name: "Chakra UI", icon: SiChakraui, className: "text-teal-500" },
  { name: "GraphQL", icon: SiGraphql, className: "text-pink-600" },
  { name: "Apollo", icon: SiApollographql },
  { name: "REST APIs", icon: SiOpenapiinitiative, className: "text-lime-600" },
  { name: "WordPress", icon: SiWordpress },
  { name: "Laravel", icon: SiLaravel, className: "text-red-500" },
  { name: "Vite", icon: SiVite, className: "text-purple-500" },
  { name: "Prisma", icon: SiPrisma, className: "text-emerald-500" },
  { name: "PostgreSQL", icon: SiPostgresql, className: "text-blue-500" },
  { name: "MySQL", icon: SiMysql, className: "text-sky-600" },
  { name: "Supabase", icon: SiSupabase, className: "text-emerald-500" },
  { name: "Firebase", icon: SiFirebase, className: "text-yellow-500" },
  {
    name: "Artificial Intelligence",
    icon: BsRobot,
    className: "text-rose-500",
  },
  { name: "Node.js", icon: SiNodedotjs, className: "text-green-600" },
  { name: "NestJS", icon: SiNestjs, className: "text-red-600" },
  { name: "WXT", icon: SiWxt, className: "text-violet-500" },
  { name: "Docker", icon: SiDocker, className: "text-sky-500" },
  { name: "Git", icon: SiGit, className: "text-orange-600" },
  { name: "GitHub", icon: SiGithub },
  { name: "Gatsby", icon: SiGatsby, className: "text-purple-600" },
  { name: "Redux", icon: SiRedux, className: "text-purple-500" },
  { name: "Webpack", icon: SiWebpack, className: "text-blue-500" },
  {
    name: "Styled Components",
    icon: SiStyledcomponents,
    className: "text-pink-500",
  },
  { name: "PWA", icon: SiPwa, className: "text-amber-600" },
  { name: "Nginx", icon: SiNginx, className: "text-green-500" },
  { name: "Jest", icon: SiJest, className: "text-red-600" },
  { name: "Storybook", icon: SiStorybook, className: "text-amber-500" },
  { name: "Socket", icon: SiSocketdotio },
  { name: "Express", icon: SiExpress },
  { name: "jQuery", icon: SiJquery },
] satisfies Stack[]
